### ISSUE TITLE
Pre-commit for documentation not working on windows

### ISSUE THREAD

**Issue by sygout** [SINTEF/ci-cd#160]
due to a at least dependency on "grep", "sed" command the pre-commit is not working on windows

**Comment by CasperWA** [comment]
Do you have a link to a workflow run that uses a callable workflow from this library as an example of this issue?

**Comment by CasperWA** [comment]
After some discussions elsewhere I think to have located the issue. It has to do with the linux commands used in the pre-commit hooks - _not_ the callable workflows (which all run in a unix environment).
