### ISSUE TITLE
Bad usage of backticks in warning message

### ISSUE THREAD

**Issue by CasperWA** [SINTEF/ci-cd#79]
As seen in [this workflow run](https://github.com/EMMC-ASBL/oteapi-core/actions/runs/3489725172/jobs/5840208487#step:7:18), the use of backticks (`) in the warning message results in some bad print outs.

**Comment by jesper-friis** [comment]
I might understand the issue. 

But backtics are a standard way to highlight variables in documentation. If the documentation system if it doesn't allow backtics in warning messages, I will say it is a bug in the documentation system rather than in the warning message.

**Comment by CasperWA** [comment]
See [the GitHub documentation](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-a-warning-message) for more information.
